### ISSUE TITLE
Final todo

### ISSUE THREAD

**Issue by benkogan** [apollo-lang/apollo#39]
This should cover everything we need to do. Please add anything that's missing.
- [x] polymorphic operation tables
- [x] type-checking for functions
- [x] closures for functions/blocks in type-checker and eval
- [x] standard library
  - function for mapping integers to some kind of music type
  - [x] `cons`
  - [x] `map`
  - [x] `reduce`/`fold`
  - [x] `filter`
  - [x] ...and versions for these for all types

if we have time:
- [ ] play function
